### ISSUE TITLE
Refactor Initialize reward vec to avoid as many db reads

### ISSUE THREAD

**Issue by girazoki** [PureStake/crowdloan-rewards#13]
Currently to know whether we should close initialization of contribution vec, we are fetching the contribution of all contributors from DB and compare it with the total pot. We should have another storage item that takes this count as contributors are added, thus ensuring we only make 1 DB read for this check. This was highlighted by the benchmarking

**Comment by JoshOrndorff** [comment]
You might not even need a separate storage item.

https://crates.parity.io/frame_support/storage/trait.StorageValue.html#method.decode_len

**Comment by JoshOrndorff** [comment]
I think this is done right?
