### ISSUE TITLE
Initialize reward vec trusts user input

### ISSUE THREAD

**Issue by JoshOrndorff** [PureStake/crowdloan-rewards#19]
Why pass in the `index` to the call rather than reading the number of accounts that are already stored.

Also, the user may specify a different `limit` each time.

**Comment by girazoki** [comment]
This approach makes sense now that we have the total number of contributors in a storage item

**Comment by JoshOrndorff** [comment]
This was solved in https://github.com/PureStake/crowdloan-rewards/pull/25
