### ISSUE TITLE
throws version error while using crowdloan-rewards with substrate-node-template

### ISSUE THREAD

**Issue by lhtpavankumar** [PureStake/crowdloan-rewards#60]
I was using crowdloan-rewards-pallet branch of main, moonbeam-polkadot-v0.9.23 with substrate-node-template branch of polkadot-v0.9.23
whenever i try to compile, shows indexmap dependency is 1.7.0, but requires >1.8.0 & < 1.9.1 in cargo.lock file
I know its not recommended to manual update cargo.lock file
Is there any way that i can compile the crowdloan-pallet with substrate-node-template smoothly

**Comment by lhtpavankumar** [comment]
@girazoki kindly check the above comment & provide any valuable suggestion.

**Comment by girazoki** [comment]
Will check, can you provide a branch of substrate-node-template where I can try your compilation?

**Comment by lhtpavankumar** [comment]
https://github.com/substrate-developer-hub/substrate-node-template.git
branch - polkadot-v0.9.23

**Comment by girazoki** [comment]
but such branch does not have crowdloan-rewards incorporated right? Can you provide a branch that has it?

**Comment by lhtpavankumar** [comment]
Sorry, i dont know exact version of substrate-node-template 
But, I got know from recent commits for main & moonbeam-polkadot-v0.9.23 branches of Crowdlaon-rewards-pallet
https://github.com/PureStake/crowdloan-rewards/commit/658b06c4432b44b91a64a160ff87dba6718599e8

**Comment by girazoki** [comment]
thank you

**Comment by girazoki** [comment]
For now just change these two packages in the Cargo.lock file:

```
[[package]]
name = "indexmap"
version = "1.7.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "bc633605454125dec4b66843673f01c7df2b89479b32e0ed634e43a91cff62a5"
dependencies = [
 "autocfg",
 "hashbrown 0.11.2",
 "serde",
]
```

for 

```
[[package]]
name = "indexmap"
version = "1.8.1"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "0f647032dfaa1f8b6dc29bd3edb7bbef4861b8b8007ebb118d6db284fd59f6ee"
dependencies = [
 "autocfg",
 "hashbrown 0.11.2",
 "serde",
]
```

and 

```
[[package]]
name = "petgraph"
version = "0.6.1"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "51b305cc4569dd4e8765bab46261f67ef5d4d11a4b6e745100ee5dad8948b46c"
dependencies = [
 "fixedbitset",
 "indexmap",
]
```

for 

```
[[package]]
name = "petgraph"
version = "0.6.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "4a13a2fa9d0b63e5f22328828741e523766fff0ee9e779316902290dff3f824f"
dependencies = [
 "fixedbitset",
 "indexmap",
]
```

**Comment by girazoki** [comment]
It compiles with that for me. Next week I will try to re-visit https://github.com/PureStake/crowdloan-rewards/pull/44 so that the polkadot dependencies (which are causing trouble) dont get injected

**Comment by lhtpavankumar** [comment]
Ok, Thank You @girazoki for hep

**Comment by vishal33singh** [comment]
using indexmap = "1.9.1"    this worked for me. now "impl pallet_crowdloan_rewards" are asking for some values.......        

 impl pallet_crowdloan_rewards::Config for Runtime {
	type Event = Event;
	type RelayChainAccountId = sp_runtime::AccountId32;
	type RewardCurrency = Balances;
	type VestingPeriod = VestingPeriod;
	type Initialized;
	type InitializationPayment;
	type MaxInitContributors;
	type MinimumReward;
	type RewardAddressRelayVoteThreshold;
	type RewardAddressChangeOrigin;
	type SignatureNetworkIdentifier;
	type RewardAddressAssociateOrigin;
	type VestingBlockNumber;
	type VestingBlockProvider;
	type WeightInfo;
}

**Comment by girazoki** [comment]
Yeah, those are configuration values. You need to set those according to what you want in the runtime

**Comment by girazoki** [comment]
@vishal33singh We merged a PR that removes all cumulus dependencies. This should help with any further issues you encounter in the Cargo.lock.

Can I close this issue?

**Comment by girazoki** [comment]
Closing, let us know if you need to re-open it
