### ISSUE TITLE
`payable_per_block` suffers from integer division truncation

### ISSUE THREAD

**Issue by notlesh** [PureStake/crowdloan-rewards#9]
The calculation for paying out a reward currently "rounds down" as a result of integer division. This result is then amplified by the number of blocks used to calculate how much should be paid over time, effectively dampening the payout rate.

The relevant code starts [here](https://github.com/PureStake/crowdloan-rewards/blob/5088641d12d2a7a00ee01527db232d739af3e926/src/lib.rs#L423). 

As an extreme example, if `payable_per_block` were calculated as `2/3` (e.g. `info.total_reward - first_paid == 2` and `T::VestingPeriod::get() == 3`), the result would be 0 (because `floor(2/3) == 0`). In this extreme case, no rewards would ever be paid out (as a result of lines 439/440).

The above is the case when `(info.total_reward - first_paid) < T::VestingPeriod::get()`.

In less extreme examples (such as `11/10`) the results would be that the payout rate is reduced, although the user would eventually be able to claim the entire balance (e.g. line 444).

**Comment by girazoki** [comment]
Thanks, will work on a solution for this

**Comment by girazoki** [comment]
Are we OK to pay a minimum of 1 unit in case (info.total_reward - first_paid) < T::VestingPeriod::get()?

**Comment by girazoki** [comment]
https://github.com/PureStake/crowdloan-rewards/pull/10 should solve it
